#!/bin/sh

xvfb-run -a --server-args="-screen 0 1024x768x24" \
    Xephyr -reset -br -screen 1024x768 :2 & x_pid=$!

trap "pkill -TERM -P ${x_pid}; kill ${x_pid}" EXIT

DISPLAY=:2 dbus-launch --exit-with-session dh_auto_test
